spring.application.name=servicio-usuarios
server.port=8081

spring.datasource.url=jdbc:h2:mem:usuariosdb;DB_CLOSE_DELAY=-1;MODE=LEGACY
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console 
